### ISSUE TITLE
audit file is not user writeable

### ISSUE THREAD

**Issue by PeppeLR** [Soufas/audit_history_command#1]
Hi,

audit file is not writeable by user

on caf file you need to change row 14 from:

/usr/bin/chmod 622 $FILE
to:
/usr/bin/chmod 6**66** $FILE

BR
Peppe

**Comment by Soufas** [comment]
Hi Peppe,

Thank you for your post , please note that the goal of the audit file is to be writable first by root then to be appendable only by the chattr -a command . 
The wrong comment in caf is is changed .

BR,
Seif

**Comment by PeppeLR** [comment]
Hi Soufas,

chattr +a works only for root if you don't provide write permission for all users.
I mean, this is what I understood, see my log below:

Last login: Thu Jul 16 08:48:31 2015 from 10.0.2.2
Welcome to your Vagrant-built virtual machine.
-bash: /var/audit/audit_20170705.log: Permission denied
hcmnt: file error.
[vagrant@centos7 ~ ]$ ll /var/audit/audit_20170705.log
-rw-r--r-- 1 root root 0 Jul  5 19:11 /var/audit/audit_20170705.log
-bash: /var/audit/audit_20170705.log: Permission denied
hcmnt: file error.
[vagrant@centos7 ~ ]$ lsattr /var/audit/audit_20170705.log
-----a---------- /var/audit/audit_20170705.log
-bash: /var/audit/audit_20170705.log: Permission denied
hcmnt: file error.
[vagrant@centos7 ~ ]$

does it look different for you ?

BR
Peppe

**Comment by PeppeLR** [comment]
Hi Soufas,

chattr +a works only for root if you don't provide write permission for all users.
I mean, this is what I understood, see my log below:

Last login: Thu Jul 16 08:48:31 2015 from 10.0.2.2
Welcome to your Vagrant-built virtual machine.
-bash: /var/audit/audit_20170705.log: Permission denied
hcmnt: file error.
[vagrant@centos7 ~ ]$ ll /var/audit/audit_20170705.log
-rw-r--r-- 1 root root 0 Jul  5 19:11 /var/audit/audit_20170705.log
-bash: /var/audit/audit_20170705.log: Permission denied
hcmnt: file error.
[vagrant@centos7 ~ ]$ lsattr /var/audit/audit_20170705.log
-----a---------- /var/audit/audit_20170705.log
-bash: /var/audit/audit_20170705.log: Permission denied
hcmnt: file error.
[vagrant@centos7 ~ ]$

does it look different for you ?

BR
Peppe
