### ISSUE TITLE
CentOS6 compatibility

### ISSUE THREAD

**Issue by PeppeLR** [Soufas/audit_history_command#2]
Hi,

if I try to run the module on CentOS 6.6, i receive the following error message:

==> centos6: Error: /Stage[main]/Audit_history_command::Install_config/Exec[edit_bashrc]: Failed to call refresh: Could not find command '/usr/bin/cat'
==> centos6: Error: /Stage[main]/Audit_history_command::Install_config/Exec[edit_bashrc]: Could not find command '/usr/bin/cat'
==> centos6: Error: /Stage[main]/Audit_history_command::Install_config/Exec[add_initial_audit_file]: Failed to call refresh: Could not find command '/usr/bin/mkdir'
==> centos6: Error: /Stage[main]/Audit_history_command::Install_config/Exec[add_initial_audit_file]: Could not find command '/usr/bin/mkdir'

because the sys command are located under /bin dir.

BR
Peppe

**Comment by Soufas** [comment]
Hi Peppe,

Thanks for noticing the issue , path is changed in the puppet class to include also /bin path .

BR,
Seif
